#################################################################################################################
##
## Summary: Script for generating the single-specificity-plot
## Date: 5/7/2014
## Author: Nate Olson
## Affiliation: National Institute for Standards and Technology
## Dependencies: R package ggplot2, data-single-counts.csv generated by pub_script.R
## Output files: figure-final-guess-exact.pdf
## 
#################################################################################################################

# loading dependencies
source("file_locations.R")
require(ggplot2)

# load data
ssd <- read.csv("results/data-single-specificity.csv")

ssf <- ggplot(ssd) + 
  geom_density(aes(x = value, fill = variable), alpha = 0.25) +
  scale_fill_discrete(breaks = levels(single_counts$variable), 
                      labels = c("Genus", "Strain")) +
  labs(x = "Unique counts", 
       y = "Proportion", 
       fill = "Match Level") +
  theme_bw() +
  theme(legend.justification=c(1,0), legend.position=c(1,0.60))

#sizing in relation to peerj formatting requirements
peerj_max_width = 6.7
wd = 0.5 * peerj_max_width
ht = wd

ggsave(filename="figure/figure-single-specificity.pdf",plot=ssf,width=wd, height=ht )
