#################################################################################################################
##
## Summary: Script for generating the single counts plot
## Date: 5/7/2014
## Author: Nate Olson
## Affiliation: National Institute for Standards and Technology
## Dependencies: R package ggplot2, data-single-counts.csv generated by pub_script.R
## Output files: figure-single-counts.pdf
## 
#################################################################################################################

# loading dependencies
source("file_locations.R")
require(ggplot2)

# load data
scd <- read.csv("results/data-single-counts.csv")

scp <- ggplot(scd) + 
  geom_boxplot(aes(x = variable, y= value, color = as.factor(size))) + 
  facet_grid(~target_genus) +
  scale_x_discrete(breaks = levels(single_counts$variable), 
                   labels = c("Genus", "Strain")) +
  labs(x = "Match Level", y = "Unique matches", color = "Size (bp)")+
  theme_bw() +
  theme(strip.text.x = element_text(face="italic"))

#sizing in relation to peerj formatting requirements
peerj_max_width = 6.7
wd = 1.5 * peerj_max_width
ht = wd/2

ggsave(filename="figure/figure-single-counts.pdf",plot=scp,width=wd, height=ht )
