#################################################################################################################
##
## Summary: Script for generating the contam-genus-plot
## Date: 5/7/2014
## Author: Nate Olson
## Affiliation: National Institute for Standards and Technology
## Dependencies: R package ggplot2, data-contam-genus.csv generated by pub_script.R
## Output files: figure-contam-genus.pdf
## 
#################################################################################################################

# loading dependencies
source("file_locations.R")
require(ggplot2)

# load data
cgd <- read.csv("results/data-contam-genus.csv", stringsAsFactors=FALSE)

ab_name_order <- c("B. anthracis",  "E. coli", "F. tularensis", "P. aeruginosa", 
                   "S. enterica", "S. aureus","Y. pestis" ) 
cgd$org1_name <- factor(cgd$org1_name,levels=ab_name_order)
cgd$org2_name <- factor(cgd$org2_name,levels=ab_name_order)

cgp <- ggplot(cgd) + 
  geom_raster(aes(x = org2_name, y = match_genus, fill = match_genus), show_guide = F) + 
  facet_grid(~org1_name, scale = "free_x") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(face = "italic"),
        strip.text.x = element_text(face="italic")) + 
  labs(x = "Contaminant Name", y= "Match Genus")

#sizing in relation to peerj formatting requirements
peerj_max_width = 6.7
wd = 1.5 * peerj_max_width
ht = wd/2

ggsave(filename="figure/figure-contam-genus.png",plot=cgp,width=wd, height=ht, dpi = 1200 )

