#################################################################################################################
##
## Summary: Script for generating the contam-LOD-plot
## Date: 5/7/2014
## Author: Nate Olson
## Affiliation: National Institute for Standards and Technology
## Dependencies: R package ggplot2, data-contam-LOD.csv generated by pub_script.R
## Output files: figure-final-guess-exact.pdf
## 
#################################################################################################################

# loading dependencies
source("file_locations.R")
require(ggplot2)

# load data
cld <- read.csv("results/data-contam-LOD.csv")
cld$org1_name <- factor(cld$org1_name,levels=ab_name_order)
clf <- ggplot(cld) + 
  geom_raster(aes(y= as.factor(prop2), x = as.factor(org2_tid), fill = match_genus)) + 
  facet_grid(.~org1_name, scale = "free_x") +
  labs(y = "Contaminant Spike Level", 
       x = "Contaminant", 
       fill = "Contaminant Genus") +
  theme_bw() +
  theme(strip.text = element_text(face="italic"), 
        legend.position = "bottom", 
        legend.direction="horizontal",
        axis.text.x = element_blank())

#sizing in relation to peerj formatting requirements
peerj_max_width = 6.7
wd = 1.5 * peerj_max_width
ht = wd/2

ggsave(filename="figure/figure-contam-LOD.png",plot=clf,width=wd, height=ht, dpi=1200)
