#################################################################################################################
##
## Summary: Script for generating the final-guess-exact-plot
## Date: 5/7/2014
## Author: Nate Olson
## Affiliation: National Institute for Standards and Technology
## Dependencies: R package ggplot2, data-single-counts.csv generated by pub_script.R
## Output files: figure-final-guess-exact.pdf
## 
#################################################################################################################

# loading dependencies
source("file_locations.R")
require(ggplot2)

# load data
fgd <- read.csv("results/data-final-guess.csv")

fgep <- qplot(x = Final.Guess, data = fgd[fgd$match == "exact",], geom= "bar") + 
  scale_x_log10() + 
  theme_bw() + 
  labs(x = "Estimated Proportions", y = "Abundance")

#sizing in relation to peerj formatting requirements
peerj_max_width = 6.7
wd = 0.5 * peerj_max_width
ht = wd

ggsave(filename="figure/figure-final-guess-exact.pdf",plot=fgep,width=wd, height=ht )

